services:
  # BACKEND: Laravel 11
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socdep-app
    restart: unless-stopped
    environment:
      - TZ=America/Mexico_City
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - /var/www/vendor # Preserva el vendor instalado en el build, no el del host
    networks:
      - socdep-network
    depends_on:
      - nosql
      - redis
    command: sh -c "php artisan config:clear && php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000 --workers=4 --max-requests=500"

  # SCHEDULER: CRON Jobs para Laravel
  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socdep-scheduler
    restart: unless-stopped
    environment:
      - TZ=America/Mexico_City
    command: php artisan schedule:work
    volumes:
      - ./backend:/var/www
      - /var/www/vendor # Preserva el vendor instalado en el build, no el del host
    networks:
      - socdep-network
    depends_on:
      - nosql
      - redis

  # WORKER: Procesador de colas (Notificaciones de No-Shows, etc.)
  queue-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socdep-worker
    restart: unless-stopped
    environment:
      - TZ=America/Mexico_City
    command: php artisan queue:work
    volumes:
      - ./backend:/var/www
      - /var/www/vendor # Preserva el vendor instalado en el build, no el del host
    networks:
      - socdep-network
    depends_on:
      - nosql
      - redis

  # FRONTEND: Vue.js + Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: socdep-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que los módulos locales sobreescriban a los del contenedor
    command: sh -c "npm install && npm run dev"
    networks:
      - socdep-network

  # REDIS: Caché y sesiones compartidas entre workers de Octane
  redis:
    image: redis:alpine
    container_name: socdep-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - socdep-network

  # NOSQL: MongoDB para Telemetría (RF-12)
  nosql:
    image: mongo:latest
    container_name: socdep-nosql
    restart: unless-stopped
    environment:
      - TZ=America/Mexico_City
    ports:
      - "27017:27017"
    networks:
      - socdep-network

networks:
  socdep-network:
    driver: bridge
